### PR TITLE
Made major breaking changes to the Mxit API wrapper.

### PR DESCRIPTION
**Pull request by rehan-vanzyl**
Notable changes:
- Moved namespace from MxitRails::MxitApi to MxitApi
- Fixed various bugs with the parameter lists of methods
- Implemented the new recommend API call
- Improved the messages of exceptions

### CODE REVIEW

**Comment by drubin** [comment]
Looks good.  Suggest bumping the version in this branch before merging? and then maybe making a tag?

**Comment by drubin** [comment]
btw I REALLY like this moving the api into his own module makes for making a mxit-api gem simplier and we can get a CLI client out of this :D

**Comment by rehan-vanzyl** [comment]
Yes, I agree having it in its own module is better.

Busy bumping version.

**Comment by linsen** [comment]
Looks good.  My only request would be to update the changelog (in changelog.md) with what's changed.

**Comment by rehan-vanzyl** [comment]
Yes, I should and will do that :)

**Pull request merged**
